
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('taskClasses').del()
    .then(function () {
      return Promise.all([
        // Inserts seed entries
        knex('taskClasses').insert({task: 'eat sushi', class: 'e'}),
        knex('taskClasses').insert({task: 'eat dinner', class: 'e'}),
        knex('taskClasses').insert({task: 'eat breakfast', class: 'e'}),
        knex('taskClasses').insert({task: 'eat dinner', class: 'e'}),
        knex('taskClasses').insert({task: 'eat supper', class: 'e'}),
        knex('taskClasses').insert({task: 'eat pork', class: 'e'}),
        knex('taskClasses').insert({task: 'eat chicken', class: 'e'}),
        knex('taskClasses').insert({task: 'eat fish', class: 'e'}),
        knex('taskClasses').insert({task: 'eat meat', class: 'e'}),
        knex('taskClasses').insert({task: 'eat snake meat', class: 'e'}),
        knex('taskClasses').insert({task: 'eat goat meat', class: 'e'}),
        knex('taskClasses').insert({task: 'eat duck', class: 'e'}),
        knex('taskClasses').insert({task: 'eat duck liver', class: 'e'}),
        knex('taskClasses').insert({task: 'eat port liver', class: 'e'}),
        knex('taskClasses').insert({task: 'eat chicken liver', class: 'e'}),
        knex('taskClasses').insert({task: 'eat fish liver', class: 'e'}),
        knex('taskClasses').insert({task: 'eat ISIS liver', class: 'e'}),
        knex('taskClasses').insert({task: 'eat ISIS heart', class: 'e'}),
        knex('taskClasses').insert({task: 'eat ISIS leg', class: 'e'}),
        knex('taskClasses').insert({task: 'have lunch', class: 'e'}),
        knex('taskClasses').insert({task: 'have business dinner', class: 'e'}),
        knex('taskClasses').insert({task: 'have quick breakfast', class: 'e'}),
        knex('taskClasses').insert({task: 'have quick coffee', class: 'e'}),
        knex('taskClasses').insert({task: 'have lamb chop', class: 'e'}),
        knex('taskClasses').insert({task: 'drink soup', class: 'e'}),
        knex('taskClasses').insert({task: 'drink coffee', class: 'e'}),
        knex('taskClasses').insert({task: 'drink liquour', class: 'e'}),
        knex('taskClasses').insert({task: 'drink juice', class: 'e'}),
        knex('taskClasses').insert({task: 'drink apple juice', class: 'e'}),
        knex('taskClasses').insert({task: 'taste French wine', class: 'e'}),
        knex('taskClasses').insert({task: 'taste beer', class: 'e'}),
        knex('taskClasses').insert({task: 'taste California wine', class: 'e'}),
        knex('taskClasses').insert({task: 'taste Chile wine', class: 'e'}),
        knex('taskClasses').insert({task: 'taste coconut', class: 'e'}),
        knex('taskClasses').insert({task: 'delicious pear', class: 'e'}),
        knex('taskClasses').insert({task: 'delicious blueberry', class: 'e'}),
        knex('taskClasses').insert({task: 'delicious ice cream', class: 'e'}),
        knex('taskClasses').insert({task: 'takeaway pizza', class: 'e'}),
        knex('taskClasses').insert({task: 'takeway noodle', class: 'e'}),
        knex('taskClasses').insert({task: 'takeway yoghurt', class: 'e'}),

        knex('taskClasses').insert({task: 'read newspaper', class: 'r'}),
        knex('taskClasses').insert({task: 'read information', class: 'r'}),
        knex('taskClasses').insert({task: 'read New York Times', class: 'r'}),
        knex('taskClasses').insert({task: 'read Times', class: 'r'}),
        knex('taskClasses').insert({task: 'read document', class: 'r'}),
        knex('taskClasses').insert({task: 'read dissertation paper', class: 'r'}),
        knex('taskClasses').insert({task: 'read planet document', class: 'r'}),
        knex('taskClasses').insert({task: 'read house document', class: 'r'}),
        knex('taskClasses').insert({task: 'documents', class: 'r'}),
        knex('taskClasses').insert({task: 'legal documents', class: 'r'}),
        knex('taskClasses').insert({task: 'research algorithm', class: 'r'}),
        knex('taskClasses').insert({task: 'research electricity', class: 'r'}),
        knex('taskClasses').insert({task: 'research watermelon', class: 'r'}),
        knex('taskClasses').insert({task: 'research homework', class: 'r'}),
        knex('taskClasses').insert({task: 'do homework', class: 'r'}),
        knex('taskClasses').insert({task: 'do work', class: 'r'}),
        knex('taskClasses').insert({task: 'learn Java', class: 'r'}),
        knex('taskClasses').insert({task: 'learn javascript', class: 'r'}),
        knex('taskClasses').insert({task: 'learn math', class: 'r'}),
        knex('taskClasses').insert({task: 'learn Physics', class: 'r'}),
        knex('taskClasses').insert({task: 'learn Biology', class: 'r'}),
        knex('taskClasses').insert({task: 'learn knex', class: 'r'}),
        knex('taskClasses').insert({task: 'learn car repair', class: 'r'}),
        knex('taskClasses').insert({task: 'learn chemistry', class: 'r'}),
        knex('taskClasses').insert({task: 'study for exam', class: 'r'}),
        knex('taskClasses').insert({task: 'study for SAT', class: 'r'}),
        knex('taskClasses').insert({task: 'study for AP', class: 'r'}),
        knex('taskClasses').insert({task: 'study for midterm', class: 'r'}),
        knex('taskClasses').insert({task: 'study for final', class: 'r'}),
        knex('taskClasses').insert({task: 'history documents', class: 'r'}),
        knex('taskClasses').insert({task: 'old documents', class: 'r'}),
        knex('taskClasses').insert({task: 'chemistry documents', class: 'r'}),
        knex('taskClasses').insert({task: 'history book', class: 'r'}),
        knex('taskClasses').insert({task: 'chemistry book', class: 'r'}),
        knex('taskClasses').insert({task: 'math book', class: 'r'}),
        knex('taskClasses').insert({task: 'Physics book', class: 'r'}),
        knex('taskClasses').insert({task: 'little text', class: 'r'}),
        knex('taskClasses').insert({task: 'small text', class: 'r'}),
        knex('taskClasses').insert({task: 'big text', class: 'r'}),

        knex('taskClasses').insert({task: 'watch movie', class: 'w'}),
        knex('taskClasses').insert({task: 'watch TV', class: 'w'}),
        knex('taskClasses').insert({task: 'Turn on TV', class: 'w'}),
        knex('taskClasses').insert({task: 'Chinese TV', class: 'w'}),
        knex('taskClasses').insert({task: 'American TV', class: 'w'}),
        knex('taskClasses').insert({task: 'Canadian TV', class: 'w'}),
        knex('taskClasses').insert({task: 'Good TV', class: 'w'}),
        knex('taskClasses').insert({task: 'Samsung TV', class: 'w'}),
        knex('taskClasses').insert({task: 'Apple TV', class: 'w'}),
        knex('taskClasses').insert({task: 'Panasonic TV', class: 'w'}),
        knex('taskClasses').insert({task: 'Youtube snake', class: 'w'}),
        knex('taskClasses').insert({task: 'Youtube math', class: 'w'}),
        knex('taskClasses').insert({task: 'Youtube Physics', class: 'w'}),
        knex('taskClasses').insert({task: 'Youtube first class', class: 'w'}),
        knex('taskClasses').insert({task: 'youtube dog', class: 'w'}),
        knex('taskClasses').insert({task: 'youtube CNN', class: 'w'}),
        knex('taskClasses').insert({task: 'documentary CNN', class: 'w'}),
        knex('taskClasses').insert({task: 'documentary BBC', class: 'w'}),
        knex('taskClasses').insert({task: 'documentary ABC', class: 'w'}),
        knex('taskClasses').insert({task: 'old documentary', class: 'w'}),
        knex('taskClasses').insert({task: 'HBO', class: 'w'}),
        knex('taskClasses').insert({task: 'BBC', class: 'w'}),
        knex('taskClasses').insert({task: 'CNN', class: 'w'}),
        knex('taskClasses').insert({task: 'ABC', class: 'w'}),
        knex('taskClasses').insert({task: 'CCTV', class: 'w'}),
        knex('taskClasses').insert({task: 'CBS', class: 'w'}),
        knex('taskClasses').insert({task: 'CTV', class: 'w'}),
        knex('taskClasses').insert({task: 'movie The Interview', class: 'w'}),
        knex('taskClasses').insert({task: 'movie The Martian', class: 'w'}),
        knex('taskClasses').insert({task: 'movie The Unicorn', class: 'w'}),
        knex('taskClasses').insert({task: 'movie night', class: 'w'}),
        knex('taskClasses').insert({task: 'SilverCity Burnaby', class: 'w'}),
        knex('taskClasses').insert({task: 'SilverCity Richmond', class: 'w'}),
        knex('taskClasses').insert({task: 'SilverCity Vancouver', class: 'w'}),
        knex('taskClasses').insert({task: 'Oslo theatre', class: 'w'}),
        knex('taskClasses').insert({task: 'Cannes theatre', class: 'w'}),
        knex('taskClasses').insert({task: 'Wuxi theatre', class: 'w'}),
        knex('taskClasses').insert({task: 'Shanghai theatre', class: 'w'}),
        knex('taskClasses').insert({task: 'Osaka theatre', class: 'w'}),
        knex('taskClasses').insert({task: 'Seoul theatre', class: 'w'}),
        knex('taskClasses').insert({task: 'Pyongyang show', class: 'w'}),
        knex('taskClasses').insert({task: 'Hong Kong show', class: 'w'}),
        knex('taskClasses').insert({task: 'Taiwan show', class: 'w'}),
        knex('taskClasses').insert({task: 'London show', class: 'w'}),
        knex('taskClasses').insert({task: 'Paris show', class: 'w'}),
        knex('taskClasses').insert({task: 'Geneva show', class: 'w'}),
        knex('taskClasses').insert({task: 'Tonight show', class: 'w'}),

        knex('taskClasses').insert({task: 'buy food', class: 'b'}),
        knex('taskClasses').insert({task: 'buy gas', class: 'b'}),
        knex('taskClasses').insert({task: 'buy bear', class: 'b'}),
        knex('taskClasses').insert({task: 'buy ticket', class: 'b'}),
        knex('taskClasses').insert({task: 'buy milk', class: 'b'}),
        knex('taskClasses').insert({task: 'buy flowers', class: 'b'}),
        knex('taskClasses').insert({task: 'buy house', class: 'b'}),
        knex('taskClasses').insert({task: 'buy a ring', class: 'b'}),
        knex('taskClasses').insert({task: 'buy a book', class: 'b'}),
        knex('taskClasses').insert({task: 'buy a car', class: 'b'}),
        knex('taskClasses').insert({task: 'buy a pants', class: 'b'}),
        knex('taskClasses').insert({task: 'buy a computer', class: 'b'}),
        knex('taskClasses').insert({task: 'pay fees', class: 'b'}),
        knex('taskClasses').insert({task: 'pay for fees', class: 'b'}),
        knex('taskClasses').insert({task: 'pay tuition fees', class: 'b'}),
        knex('taskClasses').insert({task: 'pay late fees', class: 'b'}),
        knex('taskClasses').insert({task: 'pay her', class: 'b'}),
        knex('taskClasses').insert({task: 'tuition fees', class: 'b'}),
        knex('taskClasses').insert({task: 'late fees', class: 'b'}),
        knex('taskClasses').insert({task: 'overdraft fees', class: 'b'}),
        knex('taskClasses').insert({task: 'strata fees', class: 'b'}),
        knex('taskClasses').insert({task: 'fuel charges', class: 'b'}),
        knex('taskClasses').insert({task: 'fuel surcharges', class: 'b'}),
        knex('taskClasses').insert({task: 'extra charges', class: 'b'}),
        knex('taskClasses').insert({task: 'noodle charges', class: 'b'}),
        knex('taskClasses').insert({task: 'brown rice charges', class: 'b'}),
        knex('taskClasses').insert({task: 'get new chopsticks', class: 'b'}),
        knex('taskClasses').insert({task: 'get new fork', class: 'b'}),
        knex('taskClasses').insert({task: 'get new jeans', class: 'b'}),
        knex('taskClasses').insert({task: 'get new ties', class: 'b'}),
        knex('taskClasses').insert({task: 'get a bottle', class: 'b'}),
        knex('taskClasses').insert({task: 'get a room', class: 'b'}),
        knex('taskClasses').insert({task: 'get a computer', class: 'b'}),
        knex('taskClasses').insert({task: 'get a tablet', class: 'b'}),
      ]);
    });
};
